//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PicMan.rc
//
#define IDC_BASEITEM_MGR_DROP           3
#define IDC_FOLDER_OPEN_DROP            3
#define IDC_DIR_BTN                     3
#define IDC_BASE_PROP_BROWSE            3
#define IDC_BASEITEM_MGR_ADD            4
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_CH_PV_C1                    104
#define IDS_CH_PV_C2                    105
#define IDS_CH_PV_C3                    106
#define IDI_PICMAN                      107
#define IDS_CH_PV_C4                    107
#define IDI_SMALL                       108
#define IDS_CH_PV_C5                    108
#define IDC_PICMAN                      109
#define IDS_CH_PV_C6                    110
#define IDS_CH_PV_C7                    111
#define IDD_LOGIN                       129
#define IDD_FOLDER_OPEN                 130
#define IDD_BASEITEM_MGR                131
#define IDD_HASHTAG_EDIT                135
#define IDB_ARROWLEFT                   136
#define IDB_CANCELMOVE                  138
#define IDB_CUT                         140
#define IDB_DELETE                      141
#define IDB_DETAILS                     142
#define IDB_DOWN                        143
#define IDB_FAVORITES                   144
#define IDB_FAVORITES16                 145
#define IDB_GO                          146
#define IDB_HOME                        147
#define IDB_ICONS                       148
#define IDB_INDEX                       149
#define IDB_MAGNIFY                     150
#define IDB_MOVEAFTER                   151
#define IDB_MOVEBEFORE                  152
#define IDB_NOTLOADED                   170
#define IDB_PICTURE                     171
#define IDB_PICTURES                    172
#define IDB_PREV                        173
#define IDB_SEARCH                      174
#define IDB_SETTING                     175
#define IDB_SETTINGS                    176
#define IDB_UP                          177
#define IDI_CHECK                       180
#define IDI_CANCEL                      181
#define IDD_HASHTAG                     182
#define IDD_HASHTAGSUB                  183
#define IDD_BORDERLESS                  184
#define IDD_GLOBAL_SLIDE                185
#define IDD_GLOBAL_SLIDE_SETS           186
#define IDB_HASHTAG                     187
#define IDD_PICTURE_PROPS               189
#define IDD_DIR                         190
#define IDD_HASHTAG_MAINT               191
#define IDD_GROUP_NAME                  192
#define IDD_GROUP_SORT                  193
#define IDD_BASE_PROP                   194
#define IDD_HASHTAG_CHOOSE              195
#define IDD_HASHTAG_SELECT              196
#define IDB_EDIT                        197
#define IDB_HEART                       198
#define IDB_HEARTBREAK                  199
#define IDD_GROUP_SELECT                199
#define IDB_MAGNIFYSMALL                200
#define IDB_SHOWDUPS                    201
#define IDD_BLANK                       202
#define IDD_LANGUAGE                    203
#define IDC_LOGIN_EDIT_SERVER           1000
#define IDC_LOGIN_EDIT_USER             1001
#define IDC_LOGIN_EDIT_PWD              1002
#define IDC_LOGIN_CHECK_SHOWPWD         1003
#define IDC_LOGIN_CHECK_REMEMBER        1004
#define IDC_LOGIN_LABEL_INFO            1005
#define IDC_LOGIN_EDIT_DB               1006
#define IDC_FOLDER_OPEN_LIST            1007
#define IDC_BASEITEM_MGR_LIST           1008
#define IDC_BASEITEM_MGR_EDIT           1009
#define IDC_FOLDER_OPEN_SCAN            1010
#define IDC_HASHTAG_EDITBOX             1011
#define IDC_HASHTAG_TAB                 1012
#define IDC_HASHTAGSUB_ADD              1013
#define IDC_GLOBAL_SLIDE_START          1013
#define IDC_HASHTAG_MAINT_ADD           1013
#define IDC_GROUP_SORT_ASC              1013
#define IDC_HASHTAGSUB_EDIT             1014
#define IDC_GLOBAL_SLIDE_CHOOSE_SETS    1014
#define IDC_GLOBAL_SLIDE_LIST           1015
#define IDC_GLOBAL_SLIDE_DELAY          1016
#define IDC_GLOBAL_SLIDE_CHK_KEYS       1017
#define IDC_GLOBAL_SLIDE_SETS_LIST      1018
#define IDC_GLOBAL_SLIDE_SELECT_ALL     1018
#define IDC_GLOBAL_SLIDE_CHECK_ALL      1018
#define IDC_HASHTAG_CHOOSE_LIST         1018
#define IDC_GROUP_SELECT_LIST           1018
#define IDC_GLOBAL_SLIDE_FOLDER_SORT    1019
#define IDC_GLOBAL_SLIDE_FOLDER_RND     1020
#define IDC_GLOBAL_SLIDE_SETS           1021
#define IDC_GLOBAL_SLIDE_SETS_SORT      1022
#define IDC_GLOBAL_SLIDE_SETS_RND       1023
#define IDC_GLOBAL_SLIDE_PICS_SORT      1024
#define IDC_GLOBAL_SLIDE_PICS_RND       1025
#define IDC_GLOBAL_SLIDE_CHECK_NONE     1026
#define IDC_GLOBAL_SLIDE_FOLDERS        1027
#define IDC_GLOBAL_SLIDE_HT             1028
#define IDC_LANGUAGE_LIST               1028
#define IDC_PICPROPS_FILE_DIR           1029
#define IDC_GLOBAL_SLIDE_CHK_LIGHT      1029
#define IDC_PICPROPS_FILE_NAME          1030
#define IDC_PICPROPS_FILE_PART          1031
#define IDC_PICPROPS_FILE_NMBR          1032
#define IDC_PICPROPS_FILE_MC            1033
#define IDC_PICPROPS_FILE_WIDTH         1034
#define IDC_HASHTAG_PH                  1034
#define IDC_PICPROPS_FILE_HEIGHT        1035
#define IDC_DIR_EDIT                    1035
#define IDC_PICPROPS_FILE_DATE          1036
#define IDC_HASHTAG_MAINT_EDIT          1036
#define IDC_GROUP_NAME_EDIT             1036
#define IDC_BASE_PROP_ID                1036
#define IDC_PICPROPS_DB_BASE_ID         1037
#define IDC_GROUP_NAME_MSG              1037
#define IDC_BASE_PROP_NAME              1037
#define IDC_PICPROPS_DB_FLDR_ID         1038
#define IDC_GROUP_SORT_R1               1038
#define IDC_BASE_PROP_DIR               1038
#define IDC_PICPROPS_DB_PIC_ID          1039
#define IDC_GROUP_SORT_R3               1039
#define IDC_PICPROPS_DB_ADDED           1040
#define IDC_GROUP_SORT_R2               1040
#define IDC_PICPROPS_DB_BASE_NAME       1041
#define IDC_GROUP_SORT_R4               1041
#define IDC_PICPROPS_DB_BASE_PATH       1042
#define IDC_GROUP_SORT_R5               1042
#define IDC_PICPROPS_DB_FLDR_NAME       1043
#define IDC_GROUP_SORT_R6               1043
#define IDC_PICPROPS_DB_PIC_NAME        1044
#define IDC_HASHTAG_SELECT_EDIT         1045
#define IDC_HASHTAG_SELECT_ADD          1046
#define IDC_GLOBAL_SLIDE_HELP           1047
#define IDC_STATIC_IMG                  1048
#define IDC_ABOUT_STATIC_1              1049
#define IDC_ABOUT_STATIC_2              1050
#define IDC_BASE_PROP_STATIC_1          1051
#define IDC_BASE_PROP_STATIC_2          1052
#define IDC_BASE_PROP_STATIC_3          1053
#define IDC_GLOBAL_SLIDE_1              1054
#define IDC_GLOBAL_SLIDE_2              1055
#define IDC_LOGIN_1                     1056
#define IDC_LOGIN_2                     1057
#define IDC_LOGIN_3                     1058
#define IDC_LOGIN_4                     1059
#define IDC_PIC_PROPS_2                 1060
#define IDC_PIC_PROPS_0                 1061
#define IDC_PIC_PROPS_3                 1062
#define IDC_PIC_PROPS_4                 1063
#define IDC_PIC_PROPS_5                 1064
#define IDC_PIC_PROPS_6                 1065
#define IDC_PIC_PROPS_7                 1066
#define IDC_PIC_PROPS_8                 1067
#define IDC_PIC_PROPS_9                 1068
#define IDC_PIC_PROPS_10                1069
#define IDC_PIC_PROPS_11                1070
#define IDC_PIC_PROPS_12                1071
#define IDC_PIC_PROPS_13                1072
#define IDC_PIC_PROPS_14                1073
#define IDC_PIC_PROPS_15                1074
#define IDC_PIC_PROPS_16                1075
#define IDC_PIC_PROPS_17                1076
#define IDC_BASEITEM_MGR_OK             1077
#define IDC_FOLDER_OPEN_OK              1078
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         33009
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           121
#endif
#endif
