//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PicMan.rc
//
#define IDS_APP_TITLE                   106
#define IDD_ABOUTBOX                    107
#define IDM_ABOUT                       108
#define IDI_PICMAN                      112
#define IDI_SMALL                       114
#define IDC_PICMAN                      116
#define IDD_LOGIN                       119
#define IDD_FOLDER_OPEN                 120
#define IDD_BASEITEM_MGR                121
#define IDD_HASHTAG_EDIT                122
#define IDB_CANCELMOVE                  124
#define IDB_CUT                         125
#define IDB_DELETE                      126
#define IDB_DETAILS                     127
#define IDB_DOWN                        128
#define IDB_FAVORITES16                 130
#define IDB_ICONS                       133
#define IDB_MOVEAFTER                   136
#define IDB_MOVEBEFORE                  137
#define IDB_SETTINGS                    144
#define IDB_UP                          145
#define IDI_CHECK                       146
#define IDI_CANCEL                      147
#define IDD_HASHTAG                     148
#define IDD_HASHTAGSUB                  149
#define IDD_BORDERLESS                  150
#define IDD_GLOBAL_SLIDE                151
#define IDD_GLOBAL_SLIDE_SETS           152
#define IDB_HASHTAG                     153
#define IDD_PICTURE_PROPS               154
#define IDD_DIR                         155
#define IDD_HASHTAG_MAINT               156
#define IDD_GROUP_NAME                  157
#define IDD_GROUP_SORT                  158
#define IDD_BASE_PROP                   159
#define IDD_HASHTAG_CHOOSE              160
#define IDD_HASHTAG_SELECT              161
#define IDB_EDIT                        162
#define IDB_HEART                       163
#define IDB_HEARTBREAK                  164
#define IDD_GROUP_SELECT                165
#define IDB_MAGNIFYSMALL                166
#define IDB_SHOWDUPS                    167
#define IDD_BLANK                       168
#define IDD_LANGUAGE                    169
#define IDD_DUP_PERCENT                 170
#define IDD_HASHTAGSET_CHOOSE           171
#define IDC_LOGIN_EDIT_SERVER           1000
#define IDC_LOGIN_EDIT_USER             1001
#define IDC_LOGIN_EDIT_PWD              1002
#define IDC_LOGIN_CHECK_SHOWPWD         1003
#define IDC_LOGIN_CHECK_REMEMBER        1004
#define IDC_LOGIN_LABEL_INFO            1005
#define IDC_LOGIN_EDIT_DB               1006
#define IDC_FOLDER_OPEN_LIST            1007
#define IDC_BASEITEM_MGR_LIST           1008
#define IDC_BASEITEM_MGR_EDIT           1009
#define IDC_FOLDER_OPEN_SCAN            1010
#define IDC_HASHTAG_EDITBOX             1011
#define IDC_HASHTAG_TAB                 1012
#define IDC_HASHTAGSUB_ADD              1013
#define IDC_GLOBAL_SLIDE_START          1014
#define IDC_HASHTAG_MAINT_ADD           1015
#define IDC_GROUP_SORT_ASC              1016
#define IDC_HASHTAGSUB_EDIT             1017
#define IDC_GLOBAL_SLIDE_CHOOSE_SETS    1018
#define IDC_GLOBAL_SLIDE_LIST           1019
#define IDC_GLOBAL_SLIDE_DELAY          1020
#define IDC_GLOBAL_SLIDE_CHK_KEYS       1021
#define IDC_GLOBAL_SLIDE_SETS_LIST      1022
#define IDC_GLOBAL_SLIDE_SELECT_ALL     1023
#define IDC_GLOBAL_SLIDE_CHECK_ALL      1024
#define IDC_HASHTAG_CHOOSE_LIST         1025
#define IDC_GROUP_SELECT_LIST           1026
#define IDC_GLOBAL_SLIDE_FOLDER_SORT    1027
#define IDC_GLOBAL_SLIDE_FOLDER_RND     1028
#define IDC_GLOBAL_SLIDE_SETS           1029
#define IDC_GLOBAL_SLIDE_SETS_SORT      1030
#define IDC_GLOBAL_SLIDE_SETS_RND       1031
#define IDC_GLOBAL_SLIDE_PICS_SORT      1032
#define IDC_GLOBAL_SLIDE_PICS_RND       1033
#define IDC_GLOBAL_SLIDE_CHECK_NONE     1034
#define IDC_GLOBAL_SLIDE_FOLDERS        1035
#define IDC_GLOBAL_SLIDE_HT             1036
#define IDC_LANGUAGE_LIST               1037
#define IDC_PICPROPS_FILE_DIR           1038
#define IDC_GLOBAL_SLIDE_CHK_LIGHT      1039
#define IDC_PICPROPS_FILE_NAME          1040
#define IDC_PICPROPS_FILE_PART          1041
#define IDC_PICPROPS_FILE_NMBR          1042
#define IDC_PICPROPS_FILE_MC            1043
#define IDC_PICPROPS_FILE_WIDTH         1044
#define IDC_HASHTAG_PH                  1044
#define IDC_PICPROPS_FILE_HEIGHT        1045
#define IDC_DIR_EDIT                    1046
#define IDC_PICPROPS_FILE_DATE          1047
#define IDC_HASHTAG_MAINT_EDIT          1048
#define IDC_GROUP_NAME_EDIT             1049
#define IDC_BASE_PROP_ID                1050
#define IDC_PICPROPS_DB_BASE_ID         1051
#define IDC_GROUP_NAME_MSG              1052
#define IDC_BASE_PROP_NAME              1053
#define IDC_PICPROPS_DB_FLDR_ID         1054
#define IDC_GROUP_SORT_R1               1055
#define IDC_BASE_PROP_DIR               1056
#define IDC_PICPROPS_DB_PIC_ID          1057
#define IDC_GROUP_SORT_R3               1058
#define IDC_PICPROPS_DB_ADDED           1059
#define IDC_GROUP_SORT_R2               1060
#define IDC_PICPROPS_DB_BASE_NAME       1061
#define IDC_GROUP_SORT_R4               1062
#define IDC_PICPROPS_DB_BASE_PATH       1063
#define IDC_GROUP_SORT_R5               1064
#define IDC_PICPROPS_DB_FLDR_NAME       1065
#define IDC_GROUP_SORT_R6               1066
#define IDC_PICPROPS_DB_PIC_NAME        1067
#define IDC_HASHTAG_SELECT_EDIT         1068
#define IDC_HASHTAG_SELECT_ADD          1069
#define IDC_GLOBAL_SLIDE_HELP           1070
#define IDC_STATIC_IMG                  1071
#define IDC_ABOUT_STATIC_1              1072
#define IDC_ABOUT_STATIC_2              1073
#define IDC_BASE_PROP_STATIC_1          1074
#define IDC_BASE_PROP_STATIC_2          1075
#define IDC_BASE_PROP_STATIC_3          1076
#define IDC_GLOBAL_SLIDE_1              1077
#define IDC_GLOBAL_SLIDE_2              1078
#define IDC_LOGIN_1                     1079
#define IDC_LOGIN_2                     1080
#define IDC_LOGIN_3                     1081
#define IDC_LOGIN_4                     1082
#define IDC_PIC_PROPS_2                 1083
#define IDC_PIC_PROPS_0                 1084
#define IDC_PIC_PROPS_3                 1085
#define IDC_PIC_PROPS_4                 1086
#define IDC_PIC_PROPS_5                 1087
#define IDC_PIC_PROPS_6                 1088
#define IDC_PIC_PROPS_7                 1089
#define IDC_PIC_PROPS_8                 1090
#define IDC_PIC_PROPS_9                 1091
#define IDC_PIC_PROPS_10                1092
#define IDC_PIC_PROPS_11                1093
#define IDC_PIC_PROPS_12                1094
#define IDC_PIC_PROPS_13                1095
#define IDC_PIC_PROPS_14                1096
#define IDC_PIC_PROPS_15                1097
#define IDC_PIC_PROPS_16                1098
#define IDC_PIC_PROPS_17                1099
#define IDC_BASEITEM_MGR_OK             1100
#define IDC_FOLDER_OPEN_OK              1101
#define IDC_BASEITEM_MGR_DROP           1102
#define IDC_FOLDER_OPEN_DROP            1103
#define IDC_DIR_BTN                     1104
#define IDC_BASE_PROP_BROWSE            1105
#define IDC_BASEITEM_MGR_ADD            1106
#define IDC_DUP_PERCENT_EDIT            1110
#define IDC_DUP_PERCENT_LABEL1          1111
#define IDC_DUP_PERCENT_LABEL2          1112
#define IDC_DUP_PERCENT_CL1             1117
#define IDC_DUP_PERCENT_CL2             1118
#define IDC_DUP_PERCENT_CL3             1119
#define IDC_DUP_PERCENT_GL              1120
#define IDC_DUP_PERCENT_GR              1121
#define IDC_PICPROPS_THUMB              1122
#define IDC_DUP_PERCENT_CR1             1123
#define IDC_HASHTAGSET_CHOOSE_LIST      1123
#define IDC_DUP_PERCENT_CR2             1124
#define IDC_PICPROPS_DB_HASHTAGS        1124
#define IDC_DUP_PERCENT_CR3             1125
#define IDC_DUP_PERCENT_CL4             1126
#define IDC_DUP_PERCENT_CR4             1127
#define IDC_DUP_PERCENT_CL5             1128
#define IDC_DUP_PERCENT_CL6             1129
#define IDC_DUP_PERCENT_CR5             1130
#define IDC_DUP_PERCENT_CR6             1131
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         33009
#define _APS_NEXT_CONTROL_VALUE         1125
#define _APS_NEXT_SYMED_VALUE           121
#endif
#endif
